//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klijent
    {
        public int Id { get; set; }
        public string Naziv_klijenta { get; set; }
        public string Sediste { get; set; }
        public int Ziroracun { get; set; }
    }
}
