//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KlijentskiProjekti
    {
        public int Id_klijent { get; set; }
        public int Id_projekat { get; set; }
        public System.DateTime Datum_potpisivanja_ugovora { get; set; }
        public int Vrednost_projekta { get; set; }
    }
}
