//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FudbalskiKup.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiplomskiBazaEntities : DbContext
    {
        public DiplomskiBazaEntities()
            : base("name=DiplomskiBazaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Grad> Grads { get; set; }
        public virtual DbSet<Igra> Igras { get; set; }
        public virtual DbSet<Igrac> Igracs { get; set; }
        public virtual DbSet<Karta> Kartas { get; set; }
        public virtual DbSet<Kupuje> Kupujes { get; set; }
        public virtual DbSet<LicnaNagrada> LicnaNagradas { get; set; }
        public virtual DbSet<Nagrada> Nagradas { get; set; }
        public virtual DbSet<Navijac> Navijacs { get; set; }
        public virtual DbSet<Odrzava> Odrzavas { get; set; }
        public virtual DbSet<Stadion> Stadions { get; set; }
        public virtual DbSet<sudija> sudijas { get; set; }
        public virtual DbSet<Tim> Tims { get; set; }
        public virtual DbSet<TimskaNagrada> TimskaNagradas { get; set; }
        public virtual DbSet<Utakmica> Utakmicas { get; set; }
    }
}
