//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FudbalskiKup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Igra
    {
        public int Tim_TimID { get; set; }
        public int Utakmica_UtakmicaID { get; set; }
        public int Sudija_SudijaID { get; set; }
        public Nullable<int> BrojGolova { get; set; }
    
        public virtual sudija sudija { get; set; }
        public virtual Tim Tim { get; set; }
        public virtual Utakmica Utakmica { get; set; }
    }
}
