//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FudbalskiKup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kupuje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kupuje()
        {
            this.Odrzava = new HashSet<Odrzava>();
        }
    
        public int Karta_KartaID { get; set; }
        public int Korisnik_KorisnikID { get; set; }
    
        public virtual Karta Karta { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odrzava> Odrzava { get; set; }
        public virtual Kupuje Kupuje1 { get; set; }
        public virtual Kupuje Kupuje2 { get; set; }
    }
}
