//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FudbalskiKup.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DiplomskiBazaEntities : DbContext
    {
        public DiplomskiBazaEntities()
            : base("name=DiplomskiBazaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Grad> Grad { get; set; }
        public virtual DbSet<Igra> Igra { get; set; }
        public virtual DbSet<Igrac> Igrac { get; set; }
        public virtual DbSet<Karta> Karta { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<Kupuje> Kupuje { get; set; }
        public virtual DbSet<LicnaNagrada> LicnaNagrada { get; set; }
        public virtual DbSet<Nagrada> Nagrada { get; set; }
        public virtual DbSet<Odrzava> Odrzava { get; set; }
        public virtual DbSet<Stadion> Stadion { get; set; }
        public virtual DbSet<sudija> sudija { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tim> Tim { get; set; }
        public virtual DbSet<TimskaNagrada> TimskaNagrada { get; set; }
        public virtual DbSet<Utakmica> Utakmica { get; set; }
    
        public virtual int IzracunajUkopneGolove(Nullable<int> brGolova1, Nullable<int> brGolova2, ObjectParameter rezultat)
        {
            var brGolova1Parameter = brGolova1.HasValue ?
                new ObjectParameter("brGolova1", brGolova1) :
                new ObjectParameter("brGolova1", typeof(int));
    
            var brGolova2Parameter = brGolova2.HasValue ?
                new ObjectParameter("brGolova2", brGolova2) :
                new ObjectParameter("brGolova2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IzracunajUkopneGolove", brGolova1Parameter, brGolova2Parameter, rezultat);
        }
    
        public virtual int IzracunajIndeksnePoene(Nullable<int> asistencije, Nullable<int> brGolova, ObjectParameter indeksinPoeni)
        {
            var asistencijeParameter = asistencije.HasValue ?
                new ObjectParameter("asistencije", asistencije) :
                new ObjectParameter("asistencije", typeof(int));
    
            var brGolovaParameter = brGolova.HasValue ?
                new ObjectParameter("brGolova", brGolova) :
                new ObjectParameter("brGolova", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IzracunajIndeksnePoene", asistencijeParameter, brGolovaParameter, indeksinPoeni);
        }
    }
}
